### ISSUE TITLE
Cannot be installed in editable mode

### ISSUE THREAD

**Issue by RodBelaFarin** [RoboCoachTechnologies/ROScribe#3] opened 2023-11-30 18:09 UTC
Following the installation instructions from [here](https://github.com/RoboCoachTechnologies/ROScribe/wiki/1.-Installation) I am getting the following error when trying to run the `pip install -e .` command (yes, I did include the dot):

`ERROR: Project file:///home/${USERNAME}/code_tests/ROScribe has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.`

**Comment by ErikParkerrr** [comment] 2023-11-30 21:05
Hi I have the same exact issue

**Comment by RoboCoachTech** [comment] 2023-12-01 05:53
Thanks for the feedback. We're gonna look into it and get back to you shortly.

**Comment by RoboCoachian** [comment] 2023-12-01 20:13
Hi @RodBelaFarin and @ErikParkerrr,

The problem might be caused by a deprecated `setuptools` version, or multiple versions of `setuptools` installed on your machine while the deprecated version being called during the installation.

I suggest trying one of the following solutions:

1. [Best practice] Installing `ROScribe` inside a virtual environment. This will ensure you won't overwrite any of your existing python packages by isolating `ROScribe` installation from your _system_ installed packages.
2. Installing `ROScribe` without `editable` flag: `pip install .`
This is not recommended since you will need to run `pip install .` every time you make a change in the code in order to see the effects.
3. You can also install newer versions of `pip` (≥ 21.3) and `setuptools` (≥ 64). This would sort out similar problems in the long-run; but personally my least favorite since it might break other _system_ installed packages.

Please let us know if trying any of the above options leads to solving your issue.

**Comment by RodBelaFarin** [comment] 2023-12-03 07:02
I was anyway going with option 2. That did work for me. Thanks!

**Comment by RoboCoachian** [comment] 2023-12-04 21:10
Glad to hear that.

I will close the issue.

**Closed as completed by RoboCoachian** 2023-12-04 21:10 UTC
